sudo: required

git:
  depth: false

services:
- docker

env:
  global:
    - SSH_KEY: /tmp/travis-buildbot.rsa
      PACKAGE_SERVER_IP: 173.14.28.193
      REPOSITORY: buster
      PKGTOOLS_COMMIT: origin/${TRAVIS_BRANCH}
      UPLOAD: scp
      PRIVILEGED: true
  jobs:
    - ARCHITECTURE: amd64

before_install:
- docker pull untangleinc/ngfw:${REPOSITORY}-build-${ARCHITECTURE}
- openssl aes-256-cbc -K $encrypted_404963842fb3_key -iv $encrypted_404963842fb3_iv -in .travis/buildbot.rsa.enc -out ${SSH_KEY} -d
- chmod 600 ${SSH_KEY}

jobs:
  include:
    - stage: build udebs & d-i
      script:
        - docker-compose -f docker-compose.build.yml run pkgtools
        - docker-compose -f docker-compose.build.yml run build
    - stage: build d-i, ISO & USB in one run
      script:
        - docker-compose -f docker-compose.build.yml run pkgtools
        - PACKAGE=d-i FORCE=1 NO_CLEAN=1 UPLOAD= docker-compose -f docker-compose.build.yml run build
        - docker-compose -f docker-compose.build.yml run build bash -c "../ngfw_pkgtools/build.sh setup-only && make iso/untangle-image iso/untangle-push"
        - docker-compose -f docker-compose.build.yml run build bash -c "../ngfw_pkgtools/build.sh setup-only && make usb/untangle-image usb/untangle-push"

notifications:
  email: false
  slack:
    rooms:
      secure: plrP2XptL2y33ok5Wvp692FEcdffgQrp8J6Yw6B7sPXZ604ZArPe6K9BCpDzioPMDwOGeFKfKa+tB8yRjO1orKxRzOKbZgO0qI4Acv35kpb/fDvkdGnBgm0gr1q1eKMwP5JlXJMcTN/LMm7INLcr91WXzuRgwYSciiKvz0FVOd8FUEber0TRfnsd4s4FTGLb2OIH/f4W5t+eS2Leeg019OlADvZOUUTk97+k3yqC8Ajl37YmjXytNR3SuEYN83AJIwON+MFMFVdfY8onyMvY+tnQqgVOy06qFnzycW4ZKrEcD0resLZim6J4Gr6FkG7F4+7EI7ZvWulmTz0RzA7WpJPCw7LH4pyEljqP0ofP92oXLpYUGn98cSyySSGCXv6/m8T9BavtpTy8N2DlTx9uDnEW2zibK0ssxRYGwCBAqGpXGGkQqPU9ccz6OzEP9wO5TJohJ9Ufo+XwyOTMyVzJUf48qlMgNN0FdUItxAO37+Yuj7rBz1Mct0UC2qO63gr0592yqP+8W1+Zvdn2R38heXTiLGoyJdDV30FJKczdTwtTUtEHo5cj1EDMECA28i6uton19OTPgchbbETe8Sg4AKhuS6tk61vepZ28jG3AA5/igigZP4f2gs7ejya7gVokAXpWOaYUXYNXHG4DWZk+CrGJqqNPGxkoauQB1RLhFOA=
    on_success: change
    on_failure: always
