sudo: required

git:
  depth: false

services:
- docker

env:
  global:
    - SSH_KEY: /tmp/travis-buildbot.rsa
  jobs:
    - REPOSITORY: buster
      DISTRIBUTION: current
      ARCHITECTURE: amd64
      PKGTOOLS_COMMIT: origin/master
      UPLOAD: scp
    # - REPOSITORY: buster
    #   DISTRIBUTION: current
    #   ARCHITECTURE: i386
    #   PKGTOOLS_COMMIT: origin/master
    #   UPLOAD: scp

before_install:
- docker pull untangleinc/ngfw:${REPOSITORY}-build
- openssl aes-256-cbc -K $encrypted_404963842fb3_key -iv $encrypted_404963842fb3_iv -in .travis/buildbot.rsa.enc -out ${SSH_KEY} -d
- chmod 600 ${SSH_KEY}

jobs:
  include:
    - stage: create pkgtools volume
      script:
        - docker-compose -f docker-compose.build.yml run pkgtools
    - stage: build udebs and d-i
      script:
        - docker-compose -f docker-compose.build.yml run build
    - stage: build and upload ISO image
      script:
        - docker-compose -f docker-compose.build.yml run build make iso/untangle-image
        - docker-compose -f docker-compose.build.yml run build make iso/untangle-push
    - stage: build and upload USB image
      script:
        - docker-compose -f docker-compose.build.yml run build make usb/untangle-image
        - docker-compose -f docker-compose.build.yml run build make usb/untangle-push

notifications:
  email: false
  slack:
    rooms:
      secure: D/60+reAXKlOXdoeDHEoQYhVRDJWZALD5ZIeIVWtOszCSxu2ej/M3tF9adkg4pLjLvROC8JmAFMIKyVXlItTGQMSqqfHGfY2uKEQtqNiWvneyNIL2cVNgDxAPI+YR2VrTuElJJ4jhoQzmIGC7XlZ6O5wls6WBXo+OQwYO8DR24nHiL2nF3RFrVIgzhSXIok0i7o574EETG2inOrPN1NlKL/CQ9Kc5aKG9nv7AOF9S+9e4zYj723KcIaaRC9gNFdhYj5lFU0BElobMgBg69uti05vRYmBf8qNCNssO05AJwJet8cZSGScqN/l9ZKpuEVdjmiN24cUGzcUDZ5LNuPbmJSgaYD+UXo0mrF/IVETv59splxUu9pcak2d9lmYRJ+ZngAara9p3ksbivDbayAFwML77/Na4cq0rm0QKVx02M5H3XF+VMa2Dn8zW6N3N6NDjX1RvGCoJmIOkwbhMZZ7AhdeLKBcdOH+bfh5oFERU+ur0qaHuiXRkcCFWvNYf8Q8HM11HjQApwdoP1SvLX0XeiSb3UCaa4UElwiCDS31IxjkSCYtqKSrTebNiU1r5A6vwE6DMTZ+jVJI/Pk9pIO2RJe922UiPaaGBeV3FzkuBS5+ICb3bRBWqaJaOF5Kqm7gkE1YH7VipThBIzLrDlQxw+Yf/q5280xREcxrpmJickM=
    on_success: change
    on_failure: always
