version: '3'

services:
    pkgtools:
      image: untangleinc/pkgtools
      environment:
        PKGTOOLS_URL: ${PKGTOOLS_URL:-https://github.com/untangle/ngfw_pkgtools}
        PKGTOOLS_COMMIT: ${PKGTOOLS_COMMIT:-origin/master}
      volumes:
        - pkgtools:/opt/untangle/ngfw_pkgtools
      entrypoint: >
        bash -c "
        git remote set-url origin $${PKGTOOLS_URL} &&
        git fetch -a &&
        git clean -f -d -x &&
        git reset --hard &&
        git checkout $${PKGTOOLS_COMMIT}"

    img_modifier_checkout:
      image: untangleinc/pkgtools
      environment:
        IMG_MODIFIER_URL: ${IMG_MODIFIER_URL:-https://github.com/untangle/ngfw_hades-pkgs}
        IMG_MODIFIER_COMMIT: ${IMG_MODIFIER_COMMIT:-origin/master}
      volumes:
        - img_modifier:/opt/untangle/img_modifier
      ## !! copy from my directory.
      entrypoint: >
        bash -c "
        mkdir -p /opt/untangle/img_modifier;
        cd /opt/untangle/img_modifier;
        [[ ! -d /opt/untangle/img_modifier/$${IMG_MODIFIER_URL##*/} ]] && git clone $${IMG_MODIFIER_URL};
        cd $$(basename -s .git $${IMG_MODIFIER_URL});
        git checkout $${IMG_MODIFIER_COMMIT};
        pwd;"

    img_modifier_apply:
      image: untangleinc/ngfw:${REPOSITORY:-buster}-build-multiarch
      environment:
        IMG_MODIFIER: ${IMG_MODIFIER:-unknown}
      volumes:
        - img_modifier:/opt/untangle/img_modifier
        - .:/opt/untangle/build
      entrypoint: >
        bash -c "
        git clean -f -d -x && git reset --hard;
        declare -x IMG_MODIFIER_DIR=$$(find ../img_modifier -name $${IMG_MODIFIER} | head -1)/ngfw_imgtools;
        echo $${IMG_MODIFIER_DIR};
        if [ -d $${IMG_MODIFIER_DIR} ]; then
           cp -r $${IMG_MODIFIER_DIR}/* .;
        fi;
        pwd"

    build_clean:
      image: untangleinc/ngfw:${REPOSITORY:-buster}-build-multiarch
      volumes:
        - .:/opt/untangle/build
      entrypoint: >
        bash -c "
        git clean -f -d -x && git reset --hard;
        pwd"

    build:
      image: untangleinc/ngfw:${REPOSITORY:-buster}-build-multiarch
      environment:
        REPOSITORY: ${REPOSITORY:-buster}
        DISTRIBUTION: ${DISTRIBUTION} # # defaults to empty: let pkgtools do the right thing
        ARCHITECTURE: ${ARCHITECTURE} # defaults to empty: build.sh will use host arch
        VERBOSE: ${VERBOSE} # defaults to empty: "not verbose"
        PACKAGE: ${PACKAGE} # defaults to empty: "all packages"
        DEBUG: ${DEBUG} # defaults to empty: "no debugging"
        SSH_KEY: ${SSH_KEY} # defaults to empty: "no key"
        NO_CLEAN: ${NO_CLEAN} # defaults to empty: "do clean"
        # empty: "no upload" (default)
        # scp: use scp method for dput
        # ftp: use ftp method for dput
        UPLOAD: ${UPLOAD}
        # empty: "do not force the build when that version is already
        # present on the target mirror (default)"
        FORCE: ${FORCE}
        TRAVIS_BRANCH: ${TRAVIS_BRANCH:-master}
        TRAVIS_PULL_REQUEST_BRANCH:
      privileged: ${PRIVILEGED:-false}
      extra_hosts:
        # from the outside, pass package-server's outside IP instead
        - "package-server:${PACKAGE_SERVER_IP:-10.112.11.105}"
      volumes:
        - .:/opt/untangle/build
        - pkgtools:/opt/untangle/ngfw_pkgtools:ro
        - img_modifier:/opt/untangle/img_modifier:ro
        - /tmp/travis-buildbot.rsa:/tmp/travis-buildbot.rsa
        - /etc/apt/apt.conf.d/01proxy:/etc/apt/apt.conf.d/01proxy

volumes:
  pkgtools:
  img_modifier:
